# ./docker-compose.yml

version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network

  mg:
    build: ./fast_api
    container_name: mg
    env_file:
      - .env
    command: ["sh", "migrate.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  back:
    build: ./fast_api
    container_name: back
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      mg:
        condition: service_completed_successfully
    command: ["sh", "entrypoint.sh"]
    ports:
      - "8000:8000"
    networks:
      - app-network


  front:
    build:
      context: ./vite_react
    container_name: front
    ports:
      - "3000:3000"
    networks:
      - app-network
