"""model Store

Revision ID: 9fc745063fbd
Revises: 3fc2c025cbac
Create Date: 2024-11-12 13:18:22.795997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc745063fbd'
down_revision: Union[str, None] = '3fc2c025cbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=True)
    op.create_table('product_store',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'store_id')
    )
    op.drop_table('product_shop')
    op.drop_index('ix_shops_id', table_name='shops')
    op.drop_index('ix_shops_name', table_name='shops')
    op.drop_table('shops')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('shops_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shops_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_shops_name', 'shops', ['name'], unique=True)
    op.create_index('ix_shops_id', 'shops', ['id'], unique=False)
    op.create_table('product_shop',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_shop_product_id_fkey'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='product_shop_shop_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'shop_id', name='product_shop_pkey')
    )
    op.drop_table('product_store')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
